[[components.redis]]

urls = [
    		"localhost:7000",
			"localhost:7001",
			"localhost:7002",
			"localhost:7003",
			"localhost:7004",
			"localhost:7005",
]

password = "123456789"

poolsize = 10

pooltimeout = 10