// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chat/internal/controller"
	"chat/internal/provider"
	"chat/internal/service"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	chatService := service.NewChatService()
	messageController := controller.NewMessageController(chatService)
	websocketServer := provider.NewWebsocketServer(messageController)
	chatController := controller.NewChatController(websocketServer, chatService)
	indexController := controller.NewIndexController()
	ginHttpServer := provider.NewHttpServer(chatController, indexController)
	toyBox := newApp(conf, ginHttpServer, websocketServer)
	return toyBox
}
